### ISSUE TITLE
Genesis / Network Launch Params

### ISSUE THREAD

**Issue by Reecepbcups** [liftedinit/manifest-ledger#1]
## TODO
- [x] PoA Admin(s) (multisig address from members)
- [x] Initial Genesis Accounts (i.e. genesis token holders + token allocations, inflation stakeholders and their %s, etc)
- [x] Validators
- [x] Update /poa module to latest v0.50.X

## Done
- [x] StakingParams 0% min rate
- [x] No inflation (see tests/interchaintest/setup.go, have to set minter and mint.params values)
- [x] Set BankMetadata for 'MFX' (umfx) token
- [x] Address prefixes of manifest
- [x] 6s block times
- [x] stable and efficient params (i.e. bonding, voting, etc). Ref hub/osmosis mostly
- [x] Tokenfactory param
- [x] manifest manual minting initially

**Comment by chalabi2** [comment]
No wasm

**Comment by Reecepbcups** [comment]
@chalabi2 I figured, thanks. Currently have it as itMs a dependency of Tokenfactory. Will mock that out

**Comment by Reecepbcups** [comment]
#14 also is handling this, left overs are required information on the manifest side

**Comment by fmorency** [comment]
Mainnet is launched!

**Comment by Reecepbcups** [comment]
Congrats!!! 🎉
